### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by raythurman2386** [raythurman2386/cognibot#53]
The current readme is a bit outdated and has a few commands that will not work. Commands will need checked to ensure any that reference running a script has the correct script location. I have recently moved all of my bash scripts into the scripts folder.

A contributing section should also be added outlining proper contribution steps and state to create issues for ideas, bugs or discussion items.

A link to join the actual discord server should be added as well. Contributors should be part of the discord.

Invite Link: https://discord.gg/MxNVnrxJJw

**Comment by AlexBurski** [comment]
I'd like to help

**Comment by raythurman2386** [comment]
> I'd like to help

Go for it.  Make yourself a branch and feel free to get familiar with the codebase for as long as you need. 

I'm working at the moment but I should be around tonight to answer any potential questions that arise. 

As you look around feel free to bring up additional issues as you see fit.

**Comment by AlexBurski** [comment]
Hi Ray,

I've been trying to start the bot but encountered some issues. The scripts didn't work on my machine, and even after following the manual setup steps, I couldn't start main.py—I'm getting a ModuleNotFoundError: No module named 'discord'. I might have missed something, but I wanted to let you know.

On a positive note, I made some updates to the README file to help clarify the setup process.

Thank you:)

**Comment by raythurman2386** [comment]
> Hi Ray,
> 
> I've been trying to start the bot but encountered some issues. The scripts didn't work on my machine, and even after following the manual setup steps, I couldn't start main.py—I'm getting a ModuleNotFoundError: No module named 'discord'. I might have missed something, but I wanted to let you know.
> 
> On a positive note, I made some updates to the README file to help clarify the setup process.
> 
> Thank you:)

Hey Alex,

I have noticed I will receive that error if I do not have the proper discord environment variables. 

For developer setup a new section may need added to the readme to walk through a development discord app for local development to that way each developer can have their own environment variables and custom testing environment.
