### ISSUE TITLE
Additional Issues Templates

### ISSUE THREAD

**Issue by raythurman2386** [raythurman2386/cognibot#55]

**Comment by AlexBurski** [comment]
Hello, I suggest adding templates for bug reports, feature requests, and documentation issues. Is there anything else you’d like to include?

**Comment by raythurman2386** [comment]
Be sure to update your repo, I pushed some documentation changes this afternoon that should help walk through setup a bit better for local development.

**Comment by AlexBurski** [comment]
Yes, thank you @raythurman2386 

I was planning to add the following section to the bug report template:

Bot Configuration (please complete the following information):

Discord Server: [e.g., Server Name]
Command Used: [e.g.,/chatgpt, /dalle]
I'm not sure if the information on Discord Server(Server Name) is entirely correct and necessary. Could you please review and approve these metrics?

**Comment by raythurman2386** [comment]
I'm not certain if the server name would be needed. 

But the channel name as well as the command name would be useful. 

I should also have a bit of logging in place for failed commands I think, so an optional time stamp for bugs could be a possibility..but that could be optional I would think.
